---
- name: update apt cache
  apt: update_cache=yes

- name: upgrade apt packages
  apt: upgrade=yes
  become: True

- name: Install required packages
  apt: name={{item}} state=present
  become: True
  with_items:
    - tmux
    - htop
    - vim
    - raspberrypi-bootloader
    - monit
    - expect
    - nmap
