---
- name: Copy install BTSync script
  copy: src=install.sh dest={{home_dir}}/btsync_install.sh mode=0744

- name: Download and extract BTSync
  shell: ./btsync_install.sh creates={{btsync_dir}}

- name: Ensure btsync storage path exists
  file: path={{btsync_storage_dir}} state=directory

- name: Copy btsync config
  template: src=btsync.conf.j2 dest={{btsync_conf}}

- name: Copy monit config
  template: src=btsync.monitrc.j2 dest=/etc/monit/conf.d/btsync.monitrc
  become: True
  notify:
    - reload monit
