---
- name: Install required packages
  apt: name={{item}} state=present
  sudo: true
  with_items:
    - ucf

- name: Update UFW default forward policy to ACCEPT
  lineinfile:
    dest=/etc/default/ufw
    regexp='^DEFAULT_FORWARD_POLICY='
    line='DEFAULT_FORWARD_POLICY="ACCEPT"'
    state=present
  notify:
    - Restart ufw
