---
- name: Copy monit config
  copy: src=monitrc dest=/etc/monit/monitrc
  sudo: true
  notify:
    - reload monit

- name: Copy systemd config
  copy: src=monit.service dest=/lib/systemd/system/monit.service
  sudo: true

- name: Start monit on boot
  systemd:
    name: monit
    state: started
  sudo: true
