---
- name: update apt cache
  apt: update_cache=yes
  become: True

- name: upgrade apt packages
  apt: upgrade=yes
  become: True

- name: Install required packages
  apt: name={{item}} state=present
  become: True
  with_items:
    - tmux
    - htop
    - vim
    - git-core
    - raspberrypi-bootloader
    - monit
    - expect
    - nmap
    - python-setuptools
    - python-crypto
    - python-markupsafe
    - python-jinja2
    - python-paramiko
    - python-pkg-resources
    - python-yaml
    - ucf
