---
#- name: Allow connections to mongoDB within local network
#  ufw:
#    proto: tcp
#    port: 27017
#    rule: allow
#    src: 192.168.1.0/24

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400
  changed_when: false

- name: Install required packages
  apt: name={{item}} state=present
  sudo: true
  with_items:
    - mongodb

- name: Ensure mongoDB is installed.
  apt:
    name: mongodb
    state: installed
- name: Copy mongoDB configuration
  template: src=mongodb.conf dest=/etc/mongodb.conf
  notify: restart mongodb

 # Install mongodb from the 10gen repository
- name: Add the Apt-key for the 10gen repository
  apt_key: id=7F0CEB10 url=http://docs.mongodb.org/10gen-gpg-key.asc

- name: Add the Apt-repository for 10gen
  apt_repository: repo="deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" state=present update_cache=yes
# See, that gives us the option to run apt-get update after too!

- name: Install MongoDB Packages and requirements
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - mongodb-10gen
    - python-pymongo
    - python-pymongo-ext
    - python-bson
    - python-bson-ext
