---
- name: Install Electrum deps
  apt: name={{item}} state=present
  sudo: true
  with_items:
    - python-qt4
    - python-pip

- name: Install Electrum
  pip: name="https://download.electrum.org/{{electrum_version}}/Electrum-{{electrum_version}}.tar.gz"
  sudo: true
