---
 - name: create postgres account
   user:
      name: postgres
      comment: "Postgres Admin"
      group: postgres

 - name: install postgresql packages
   apt: name={{item}}
   with_items:
       - postgresql
       - libpq-dev
       - python-psycopg2
   sudo: true
   remote_user: postgres

 - name: ensure database is created
   postgresql_db: 
     name: "{{dbname}}"
     owner: "{{dbuser}}"
     encoding: UTF8
     lc_ctype: "{{locale}}"
     lc_collate: "{{locale}}"
     template: template0
   sudo: true
   remote_user: postgres

 - name: ensure user has access to database
   sudo: true
   postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
   remote_user: postgres

 - name: ensure user does not have unnecessary privilege
   sudo: true
   postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
   remote_user: postgres
  
 - name: ensure no other user can access the database
   sudo: true
   postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
   remote_user: postgres
